version: "3.8"

services:
  # Backend Flask API service
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      # For development, mount the source code directory
      - ./src:/app/src
      - ./uploads:/app/src/uploads
      - ./results:/app/src/results
      - ./sample_data:/app/src/sample_data
    environment:
      - FLASK_APP=src.main:app
      - FLASK_DEBUG=1  # Enable Flask debug mode for development
      - FLASK_SECRET_KEY=a_secure_random_secret_key_for_dev_12345 # CHANGE THIS!
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USERNAME=root
      - DB_PASSWORD=password # Use a more secure password in real scenarios
      - PYTHONUNBUFFERED=1 # Ensures logs appear immediately
    depends_on:
      db: 
        condition: service_healthy # Wait for DB to be ready
    restart: unless-stopped
  
  # Frontend React development server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # React dev server port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Enables hot-reload in Windows/WSL
    depends_on:
      - api

  # Database service
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password # Use a more secure password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306" # Expose MySQL port for local development
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
        interval: 10s
        timeout: 5s
        retries: 5
    restart: unless-stopped

volumes:
  mysql_data:

