version: "3.8"

services:
  # Single container with both backend and frontend
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src.main:app
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=use_a_strong_secret_key_in_production  # CHANGE THIS!
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USERNAME=root
      - DB_PASSWORD=secure_password_here  # CHANGE THIS!
    depends_on:
      db: 
        condition: service_healthy
    restart: always

  # Database service
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secure_password_here  # CHANGE THIS!
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
        interval: 10s
        timeout: 5s
        retries: 5
    restart: always

volumes:
  mysql_data: